/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DatSketch (https://sketchfab.com/DatSketch)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/iphone-13-pro-concept-43bddf623d24406aae61c8f3ba516e3d
title: iPhone 13 Pro Concept
*/
import * as THREE from 'three';
import {useCursor, useGLTF} from '@react-three/drei';
import {GLTF} from 'three-stdlib';
import {FC, useRef, useState} from 'react';
import {useThree} from '@react-three/fiber';

type GLTFResult = GLTF & {
    nodes: {
        BackCover_Blue_0: THREE.Mesh;
        Screen_Screen_0: THREE.Mesh;
        CameraModuleBlack_BlackGlossy_0: THREE.Mesh;
        CameraModuleBlack_SpeakerAndMiic_0: THREE.Mesh;
        Bezel_BezelAndNotch_0: THREE.Mesh;
        Bezel_CameraGray_0: THREE.Mesh;
        Bezel_FrontCameraGlass_0: THREE.Mesh;
        Bezel_SpeakerAndMiic_0: THREE.Mesh;
        PowerButton_BlueGlossy_0: THREE.Mesh;
        Volume_Button_BlueGlossy_0: THREE.Mesh;
        MuteButton_BlueGlossy_0: THREE.Mesh;
        Sphere_Lens_0: THREE.Mesh;
        Camera1_CameraBlack_0: THREE.Mesh;
        Camera1_CameraMetal_0: THREE.Mesh;
        Camera1_CameraGray_0: THREE.Mesh;
        Sphere002_Lens_0: THREE.Mesh;
        Camera2_CameraBlack_0: THREE.Mesh;
        Camera2_CameraMetal_0: THREE.Mesh;
        Camera2_CameraGray_0: THREE.Mesh;
        Sphere001_Lens_0: THREE.Mesh;
        Camera3_CameraBlack_0: THREE.Mesh;
        Camera3_CameraMetal_0: THREE.Mesh;
        Camera3_CameraGray_0: THREE.Mesh;
        LiDar_LiDar_0: THREE.Mesh;
        Flash_Silver_0: THREE.Mesh;
        Flash_Flash_0: THREE.Mesh;
        CameraModuleGlass_Glass_0: THREE.Mesh;
        FrontCam_Lens_0: THREE.Mesh;
        Apple_Logo_AppleLogo_0: THREE.Mesh;
        IPHONE13_BlueGlossy_0: THREE.Mesh;
        IPHONE13_Red_0: THREE.Mesh;
        IPHONE13_BlueMatte_0: THREE.Mesh;
        IPHONE13_Silver001_0: THREE.Mesh;
        IPHONE13_SpeakerAndMiic_0: THREE.Mesh;
    };
    materials: {
        Blue: THREE.MeshStandardMaterial;
        Screen: THREE.MeshStandardMaterial;
        BlackGlossy: THREE.MeshStandardMaterial;
        SpeakerAndMiic: THREE.MeshStandardMaterial;
        BezelAndNotch: THREE.MeshStandardMaterial;
        CameraGray: THREE.MeshStandardMaterial;
        FrontCameraGlass: THREE.MeshStandardMaterial;
        BlueGlossy: THREE.MeshStandardMaterial;
        Lens: THREE.MeshStandardMaterial;
        CameraBlack: THREE.MeshStandardMaterial;
        CameraMetal: THREE.MeshStandardMaterial;
        LiDar: THREE.MeshStandardMaterial;
        Silver: THREE.MeshStandardMaterial;
        Flash: THREE.MeshStandardMaterial;
        Glass: THREE.MeshStandardMaterial;
        AppleLogo: THREE.MeshStandardMaterial;
        material: THREE.MeshStandardMaterial;
        BlueMatte: THREE.MeshStandardMaterial;
        ['Silver.001']: THREE.MeshStandardMaterial;
    };
};

export const IPhone: FC<JSX.IntrinsicElements['group'] & {onFocus: (p: THREE.Vector3, q: THREE.Quaternion) => void}> = props => {
    const ref = useRef<THREE.Group>(null);
    const {nodes, materials} = useGLTF('/assets/models/iphone.glb') as GLTFResult;
    const [hovered, hover] = useState(false);
    const {camera} = useThree();
    useCursor(hovered);
    return (
        <group
            ref={ref}
            {...props}
            name="iPhone"
            position={[-7, 0, 7]}
            rotation={[0, -2.8, 0]}
            scale={0.65}
            onPointerOver={e => (e.stopPropagation(), hover(true))}
            onPointerOut={() => hover(false)}
            onClick={e => {
                const oldPos = camera.position.clone();
                const oldQuat = camera.quaternion.clone();
                camera.position.copy(ref.current.position.clone().setY(6));
                camera.lookAt(ref.current.position);

                props.onFocus(camera.position, camera.quaternion);

                camera.position.copy(oldPos);
                camera.quaternion.copy(oldQuat);
            }}
            dispose={null}
        >
            <group>
                <mesh castShadow receiveShadow geometry={nodes.BackCover_Blue_0.geometry} material={materials.Blue} />
                <mesh castShadow receiveShadow geometry={nodes.Screen_Screen_0.geometry} material={materials.Screen} />
                <mesh castShadow receiveShadow geometry={nodes.CameraModuleBlack_BlackGlossy_0.geometry} material={materials.BlackGlossy} />
                <mesh castShadow receiveShadow geometry={nodes.CameraModuleBlack_SpeakerAndMiic_0.geometry} material={materials.SpeakerAndMiic} />
                <mesh castShadow receiveShadow geometry={nodes.Bezel_BezelAndNotch_0.geometry} material={materials.BezelAndNotch} />
                <mesh castShadow receiveShadow geometry={nodes.Bezel_CameraGray_0.geometry} material={materials.CameraGray} />
                <mesh castShadow receiveShadow geometry={nodes.Bezel_FrontCameraGlass_0.geometry} material={materials.FrontCameraGlass} />
                <mesh castShadow receiveShadow geometry={nodes.Bezel_SpeakerAndMiic_0.geometry} material={materials.SpeakerAndMiic} />
                <mesh castShadow receiveShadow geometry={nodes.PowerButton_BlueGlossy_0.geometry} material={materials.BlueGlossy} />
                <mesh castShadow receiveShadow geometry={nodes.Volume_Button_BlueGlossy_0.geometry} material={materials.BlueGlossy} />
                <mesh castShadow receiveShadow geometry={nodes.MuteButton_BlueGlossy_0.geometry} material={materials.BlueGlossy} />
                <mesh castShadow receiveShadow geometry={nodes.Sphere_Lens_0.geometry} material={materials.Lens} />
                <mesh castShadow receiveShadow geometry={nodes.Camera1_CameraBlack_0.geometry} material={materials.CameraBlack} />
                <mesh castShadow receiveShadow geometry={nodes.Camera1_CameraMetal_0.geometry} material={materials.CameraMetal} />
                <mesh castShadow receiveShadow geometry={nodes.Camera1_CameraGray_0.geometry} material={materials.CameraGray} />
                <mesh castShadow receiveShadow geometry={nodes.Sphere002_Lens_0.geometry} material={materials.Lens} />
                <mesh castShadow receiveShadow geometry={nodes.Camera2_CameraBlack_0.geometry} material={materials.CameraBlack} />
                <mesh castShadow receiveShadow geometry={nodes.Camera2_CameraMetal_0.geometry} material={materials.CameraMetal} />
                <mesh castShadow receiveShadow geometry={nodes.Camera2_CameraGray_0.geometry} material={materials.CameraGray} />
                <mesh castShadow receiveShadow geometry={nodes.Sphere001_Lens_0.geometry} material={materials.Lens} />
                <mesh castShadow receiveShadow geometry={nodes.Camera3_CameraBlack_0.geometry} material={materials.CameraBlack} />
                <mesh castShadow receiveShadow geometry={nodes.Camera3_CameraMetal_0.geometry} material={materials.CameraMetal} />
                <mesh castShadow receiveShadow geometry={nodes.Camera3_CameraGray_0.geometry} material={materials.CameraGray} />
                <mesh castShadow receiveShadow geometry={nodes.LiDar_LiDar_0.geometry} material={materials.LiDar} />
                <mesh castShadow receiveShadow geometry={nodes.Flash_Silver_0.geometry} material={materials.Silver} />
                <mesh castShadow receiveShadow geometry={nodes.Flash_Flash_0.geometry} material={materials.Flash} />
                <mesh castShadow receiveShadow geometry={nodes.CameraModuleGlass_Glass_0.geometry} material={materials.Glass} />
                <mesh castShadow receiveShadow geometry={nodes.FrontCam_Lens_0.geometry} material={materials.Lens} />
                <mesh castShadow receiveShadow geometry={nodes.Apple_Logo_AppleLogo_0.geometry} material={materials.AppleLogo} />
                <mesh castShadow receiveShadow geometry={nodes.IPHONE13_BlueGlossy_0.geometry} material={materials.BlueGlossy} />
                <mesh castShadow receiveShadow geometry={nodes.IPHONE13_Red_0.geometry} material={materials.material} />
                <mesh castShadow receiveShadow geometry={nodes.IPHONE13_BlueMatte_0.geometry} material={materials.BlueMatte} />
                <mesh castShadow receiveShadow geometry={nodes.IPHONE13_Silver001_0.geometry} material={materials['Silver.001']} />
                <mesh castShadow receiveShadow geometry={nodes.IPHONE13_SpeakerAndMiic_0.geometry} material={materials.SpeakerAndMiic} />
            </group>
        </group>
    );
};

useGLTF.preload('/assets/models/iphone.glb');
