/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Ryan_Nein (https://sketchfab.com/Ryan_Nein)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/standing-desk-65a7f4b06a5f4954a0d43eb8812dd165
title: Standing Desk
*/

import * as THREE from 'three';
import React, {useRef} from 'react';
import {useGLTF} from '@react-three/drei';
import {GLTF} from 'three-stdlib';

type GLTFResult = GLTF & {
    nodes: {
        Object_3: THREE.Mesh;
        Object_2: THREE.Mesh;
    };
    materials: {
        Legs_Material: THREE.MeshStandardMaterial;
        Desk_Top_Material: THREE.MeshStandardMaterial;
    };
};

export function Desk(props: JSX.IntrinsicElements['group']) {
    const {nodes, materials} = useGLTF('/assets/models/standing_desk.glb') as GLTFResult;
    return (
        <group {...props} dispose={null}>
            <group position={[0, -16.5, 5]} rotation={[-Math.PI / 2, 0, 0]} scale={15}>
                <mesh castShadow receiveShadow geometry={nodes.Object_3.geometry} material={materials.Legs_Material} />
                <mesh castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials.Desk_Top_Material} />
            </group>
        </group>
    );
}

useGLTF.preload('/assets/models/standing_desk.glb');
